/* Generated by Proofly React Export */
import * as React from "react";

export function ContextProviders(props: {
  children: React.ReactNode;
  locale?: string;
}): React.ReactElement;

export function FramerGroup(props: {
  children: React.ReactNode;
}): React.ReactElement;

export function WithResponsiveVariants<P extends object>(props: {
  Component: React.ComponentType<P>;
  variants: Partial<Record<"base" | "sm" | "md" | "lg" | "xl", string>>;
} & P): React.ReactElement;
