/* Generated by Proofly React Export */
import * as React from "react";

export interface HeroProps {
  title?: string;
  subtitle?: string;
}

declare const Hero: React.ComponentType<HeroProps> & {
  Responsive: React.ComponentType<HeroProps>;
};
export default Hero;
